APIAuthorizationMethods, APIPostsMethods, DomainAppEnums, HttpHeaders, HttpResponse
AT15-TestNG/WordPress-API pull request #3
Opened 2022-07-06 23:26 UTC by Agustin-Mediotti

2022-07-06 23:33 UTC, adrianovi commented on src/main/java/api/methods/APIPostsMethods.java
> +        Response res = api.post(postsEndpoint, jsonAsMap, headers);
I think the "res" should be "response" for accomplish the code conventions and have a clean code

2022-07-06 23:35 UTC, adrianovi commented on src/main/java/api/methods/APIAuthorizationMethods.java
> +        Response res = api.post(tokenEndpoint, ContentType.JSON, jsonAsMap);
"res" -> "response" for code conventions

2022-07-06 23:37 UTC, adrianovi commented on src/main/java/constants/DomainAppEnums.java
> +        SUBS("subscriber");
The enums should have the full names ADMINISTRATOR and SUBSCRIBER for accomplish code conventions and clean code

2022-07-06 23:45 UTC, Agustin-Mediotti commented on src/main/java/api/methods/APIAuthorizationMethods.java
> +        Response res = api.post(tokenEndpoint, ContentType.JSON, jsonAsMap);
Resolved all responses variable names. Please review the last commit.

2022-07-06 23:46 UTC, Agustin-Mediotti commented on src/main/java/constants/DomainAppEnums.java
> +        SUBS("subscriber");
Name of enums changed in last commit, please review the last update.

2022-07-06 23:46 UTC, Agustin-Mediotti commented on src/main/java/api/methods/APIPostsMethods.java
> +        Response res = api.post(postsEndpoint, jsonAsMap, headers);
Resolved in last commit.

2022-07-07 00:07 UTC, adrianovi approved these changes

2022-07-07 00:13 UTC, merged

2022-07-07 00:27 UTC, eliosfg requested changes
aside my below comments, all the rest looks good.

2022-07-07 00:27 UTC, eliosfg commented on src/main/java/api/APIManager.java
> +        return (instance == null) ? instance = new APIManager() : instance;
Nice!

2022-07-07 00:27 UTC, eliosfg commented on src/main/java/api/APIManager.java
> -import io.restassured.authentication.PreemptiveBasicAuthScheme;
Unused import here, fix it please

2022-07-07 00:27 UTC, eliosfg commented on src/main/java/api/methods/APIAuthorizationMethods.java
> +    private static final CredentialsManager auth = CredentialsManager.getInstance();
naming variables can be improved. I suggest apiManager and credentialsManager, for code conventions.

2022-07-07 00:27 UTC, eliosfg commented on src/main/java/api/methods/APIPostsMethods.java
> +    public static final CredentialsManager auth = CredentialsManager.getInstance();
Improve variables name

2022-07-07 00:27 UTC, eliosfg commented on src/main/java/api/methods/APIPostsMethods.java
> +        return (response.jsonPath().getString("id")) == null ? null : response;
Looks good, but in case the Post wasn't created It's necessary add the log report inside the conditional.