Created github-actions-pipeline.yml
AT15-TestNG/WordPress-API pull request #4
Opened 2022-07-07 00:00 UTC by Agustin-Mediotti

2022-07-07 00:09 UTC, adrianovi commented on .github/workflows/github-actions-pipeline.yml
> +    branches:
Perhaps it should be on all branches for the pipeline to run

2022-07-07 00:33 UTC, eliosfg requested changes

2022-07-07 00:33 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +    branches:
I think the same, you might only add '**' in replace

2022-07-07 14:34 UTC, SerJimmy requested changes

2022-07-07 14:34 UTC, SerJimmy commented on .github/workflows/github-actions-pipeline.yml
> +        run: ./gradlew clean test
It should be something like gradle clean executeFeatures -PenvId="QA01" -PcucumberOptions="@Test"

2022-07-07 15:31 UTC, eliosfg requested changes
See my comments

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +      - name: Build API Testing framework
Maybe this step could call it "Run Smoke Testing"

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +          access_token: ${{ github.token }}
It would be better if this step were in the Build stage before to run anything.

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +        run: ./gradlew sonarqube
I suggest this stage can be before the SmokeTests stage

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +      - name: Run Tests
Run Acceptance Tests

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +    needs: CodeInspection
Needs "SmokeTests" to run not "CodeInspection"

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +    needs: SmokeTests
Needs "Build" stage

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +          files: "build/test-results/**/*.xml"
Did you verify if this path is correct for reports? Remember we are using Cucumber now.

2022-07-07 15:31 UTC, eliosfg commented on .github/workflows/github-actions-pipeline.yml
> +          PUBLISH_DIR: allure-history
All this part was performed adding the Allure dependency inside the "build.gradle" file. You need to check if It is added and after that verify if the "allure-report" are being generated in the repository

2022-07-08 03:36 UTC, eliosfg approved these changes
Good job!

2022-07-08 13:05 UTC, adrianovi approved these changes

2022-07-08 13:10 UTC, SerJimmy approved these changes

2022-07-08 13:12 UTC, merged