Added GitHub Pages
AT15-TestNG/WordPress-API pull request #74
Opened 2022-07-11 15:12 UTC by Agustin-Mediotti

2022-07-11 18:04 UTC, adrianovi submitted a review, later dismissed

2022-07-11 19:01 UTC, eliosfg requested changes

2022-07-11 19:13 UTC, Agustin-Mediotti commented on .github/workflows/github-actions-pipeline.yml
> +          PUBLISH_DIR: "reports/cucumber-html-reports/overview-features.html"
Changed to requested directory

2022-07-12 01:53 UTC, jimytz approved these changes
👍

2022-07-12 01:53 UTC, adrianovi submitted a review, later dismissed

2022-07-12 02:30 UTC, eliosfg approved these changes
Good

2022-07-12 02:51 UTC, adrianovi submitted a review, later dismissed

2022-07-12 02:51 UTC, SerJimmy submitted a review, later dismissed

2022-07-12 02:51 UTC, jimytz approved these changes
💯

2022-07-12 02:54 UTC, adrianovi approved these changes

2022-07-12 02:57 UTC, merged